<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>BrandUp.MongoDB.Testing</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="EphemeralMongo" Version="3.2.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BrandUp.MongoDB\BrandUp.MongoDB.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.400" />
	</ItemGroup>

</Project>
