<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Options" />
		<PackageReference Include="MongoDB.Driver" />
		<PackageReference Include="SharpCompress" />
	</ItemGroup>

</Project>
