<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="MongoDB.Driver" Version="3.11.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BrandUp.MongoDB\BrandUp.MongoDB.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.401" />
	</ItemGroup>

</Project>
