<Project>

	<Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..'))" />

	<PropertyGroup>
		<Authors>Dmitry Kovyazin</Authors>
		<Company>BrandUp.online</Company>
		<Product>BrandUp.MongoDB</Product>
		<PackageProjectUrl>https://github.com/brandup-online/BrandUp.MongoDB</PackageProjectUrl>
		<RepositoryUrl>https://github.com/brandup-online/BrandUp.MongoDB</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageIcon>icon.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);CS1591</NoWarn>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>

	<ItemGroup>
		<None Include="$(MSBuildThisFileDirectory)..\icon.png" Pack="True" PackagePath="\" Visible="false" />
		<None Include="$(MSBuildThisFileDirectory)..\README.md" Pack="True" PackagePath="\" Visible="false" />
		<None Include="$(MSBuildThisFileDirectory)..\LICENSE" Pack="True" PackagePath="\" Visible="false" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
	</ItemGroup>

</Project>
